fix = true
target-version = "py311"

exclude = ["**/__init__.py"]
include = ["core/**/*.py", "scripts/**/*.py"]

line-length = 88

[lint]
select = ["E", "W", "F", "I", "N", "UP", "B", "C4", "T20"]
ignore = ["E501", "F401", "F821", "N999"]

[pydocstyle]
convention = "google"
